// <auto-generated />
using System;
using LMS_App.LMSDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_App.Migrations
{
    [DbContext(typeof(LMSContext))]
    [Migration("20230721061729_abc")]
    partial class abc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LMS_App.Model.LoanModel", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<string>("BorrowerInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LoanAmount")
                        .HasColumnType("float");

                    b.Property<double?>("LoanFees")
                        .HasColumnType("float");

                    b.Property<int>("LoanNumber")
                        .HasColumnType("int");

                    b.Property<int?>("LoanTerms")
                        .HasColumnType("int");

                    b.Property<string>("OriginationAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OriginationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertyInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.ToTable("LoanDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
