// <auto-generated />
using System;
using Loan_Authentication_App.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loan_Authentication_App.Migrations
{
    [DbContext(typeof(UserDB))]
    [Migration("20230722064746_lms")]
    partial class lms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Loan_Authentication_App.Models.LoanModel", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"), 1L, 1);

                    b.Property<string>("BorrowerInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LoanAmount")
                        .HasColumnType("float");

                    b.Property<double?>("LoanFees")
                        .HasColumnType("float");

                    b.Property<int>("LoanNumber")
                        .HasColumnType("int");

                    b.Property<int?>("LoanTerms")
                        .HasColumnType("int");

                    b.Property<string>("OriginationAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OriginationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertyInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.HasIndex("UserModelId");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("Loan_Authentication_App.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Loan_Authentication_App.Models.LoanModel", b =>
                {
                    b.HasOne("Loan_Authentication_App.Models.UserModel", null)
                        .WithMany("loanModels")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("Loan_Authentication_App.Models.UserModel", b =>
                {
                    b.Navigation("loanModels");
                });
#pragma warning restore 612, 618
        }
    }
}
